CREATE TABLE USERS (
 idUser INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
 email VARCHAR(32) UNIQUE NOT NULL,
 password VARCHAR(40) NOT NULL,
 active BIT NOT NULL
)

CREATE TABLE STATS(
 idStat int AUTO_INCREMENT NOT NULL PRIMARY KEY,
 idUser int NOT NULL,
 idLevel int NOT NULL,
 dateInput DATE NOT NULL,
 valueProgress DECIMAL NOT NULL,
 FOREIGN KEY (idLevel) REFERENCES LEVELS(idLevel),
 FOREIGN KEY (idUser) REFERENCES USERS(idUser) ON DELETE CASCADE
)

CREATE TABLE LEVELS(
 idLevel int AUTO_INCREMENT NOT NULL PRIMARY KEY,
 nameLevel  VARCHAR(32)  NOT NULL,
 nameCategorie VARCHAR(32) NOT NULL
)

CREATE TABLE DICTIONARY_SENTENCES(
 idDictionary int AUTO_INCREMENT NOT NULL PRIMARY KEY,
 idLevel int NOT NULL,
 sentencesENG VARCHAR(64) NOT NULL,
 sentencesPL VARCHAR(64) NOT NULL,
 FOREIGN KEY (idLevel) REFERENCES LEVELS(idLevel)
)

CREATE TABLE WORDS_PL(
 idWordPL int AUTO_INCREMENT NOT NULL PRIMARY KEY,
 wordPL VARCHAR(32) UNIQUE NOT NULL
)

CREATE TABLE WORDS_ENG(
 idWordENG int AUTO_INCREMENT NOT NULL PRIMARY KEY,
 wordENG VARCHAR(32) UNIQUE NOT NULL
)

CREATE TABLE FAMILIES(
 idFamily int AUTO_INCREMENT  NOT NULL PRIMARY KEY,
 idLevel int NOT NULL,
 headFamily  VARCHAR(32) UNIQUE NOT NULL,
 FOREIGN KEY (idLevel) REFERENCES LEVELS(idLevel)
)

CREATE TABLE DICTIONARY_WORDS(
 idDictionaryWords int AUTO_INCREMENT NOT NULL PRIMARY KEY,
 idLevel int NOT NULL,
 idFamily int,
 idWordENG int NOT NULL,
 idWordPL int NOT NULL,
 FOREIGN KEY (idLevel) REFERENCES LEVELS(idLevel),
 FOREIGN KEY (idFamily) REFERENCES FAMILIES(idFamily),
 FOREIGN KEY (idWordENG) REFERENCES WORDS_ENG(idWordENG),
 FOREIGN KEY (idWordPL) REFERENCES WORDS_PL(idWordPL)
)



